<?php
/**
 * 2015 Webmaster Gambit
 * Discuz! Develop
 * http://webmaster-gambit.ru/
 * 1.0.0
 */

if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}


$devlang = array
(
    // note related to the plug, please begin with plugins_
    'author' => 'Author',
    'add_new' => 'Add',
    // note user group, please begin with usergroups_
    'usergroups' => 'User Group',
    'usergroups_system_0' => 'ordinary user',
    'usergroups_system_1' => 'Administrators',
    'usergroups_system_2' => 'Super Moderator',
    'usergroups_system_3' => 'Moderator',
    'usergroups_system_4' => 'Prevented from speaking',
    'usergroups_system_5' => 'No Access',
    'usergroups_system_6' => 'User IP is prohibited',
    'usergroups_system_7' => 'Tourists',
    'usergroups_system_8' => 'Waiting for verification',
    'plugins' => 'Plug-in configuration',
    'plugins_home' => 'Introduction',
    'plugins_editlink' => 'Design',
    'plugins_validator' => 'Check for updates',
    'plugins_list' => 'Plug-in list',
    'plugins_system' => 'System plug',
    'plugins_install' => 'Install the new plug-in',
    'plugins_newcomment' => 'The following is a plug-in directory source/plugin/ Under not installed plugins',
    'plugins_menu' => 'Widget',
    'plugins_name' => 'Plug-in name',
    'plugins_unavailable' => 'The plug-in is not enabled',
    'plugins_empty' => 'Empty',
    'plugins_directory' => 'Plugin directory',
    'plugins_identifier' => 'The unique identifier',
    'plugins_vars_title' => 'Configuration Name (required)',
    'plugins_vars_variable' => 'Configuration variable name (required)',
    'plugins_vars_type' => 'Configuration type',
    'plugins_add' => 'Design new plug',
    'plugins_add_tips' => '<li> <b> This function is only for plug-in developers. </ B> </ li> <li> plug-in developers before using this function, please read "<a href="http://dev.discuz.org/wiki" target="_blank"> Discuz! Technology must Library </a> "in content. </ Li> <li> WARNING: Incorrect plug-in design or installation may endanger the normal use of the whole site. </ Li> ',
    'plugins_import' => 'Import plug-in data',
    'plugins_import_ignore_version' => 'allows you to import the old version of Discuz! plug (error-prone !!)',
    'plugins_update_to' => 'update to',
    'plugins_config' => 'parameter setting',
    'plugins_config_module' => 'module',
    'plugins_config_vars' => 'variable',
    'plugins_config_install' => 'installation',
    'plugins_config_uninstall' => 'Uninstall',
    'plugins_config_upgrade' => 'update',
    'plugins_config_delete' => 'Uninstall',
    'plugins_config_upgrade_other' => 'Are you sure you want to {pluginname} {version} plug-in has been updated to the following version of it? ',
    'plugins_config_uninstallplugin' => 'Uninstall this plugin',
    'plugins_edit' => 'design plug-in',
    'plugins_edit_available' => '(plug-enabled)',
    'plugins_edit_tips' =>' <li> <b> This function is only for plug-in developers, if you just install or use this plug-in, do not modify this setting. </ B> </ li> <li> plug-in developers before using this function, please read "<a href="http://dev.discuz.org/wiki" target="_blank"> Discuz! Technology must Library </a> "in content. </ Li> <li> WARNING: Incorrect plug-in design or installation may endanger the normal use of the whole site. </ Li> <li> to finish the design of the plug-publishing to <a href="http://addon.discuz.com" target="_blank"> "Discuz! Application Center" </a> share to the majority of owners . </ Li> ',
    'plugins_edit_name' => 'plug-in name (name)',
    'plugins_edit_name_comment' => 'The name of this plug-in, available in English, up to 40 bytes',
    'plugins_edit_version' => 'plug-in version number (version)',
    'plugins_edit_version_comment' => 'version of this plug-in, available in English, up to 20 bytes. When the version number is higher than the old version, the user will be prompted to install the update ',
    'plugins_edit_copyright' => 'Rights Information (copyright)',
    'plugins_edit_copyright_comment' => 'Settings widget copyright information, up to 100 bytes, once set can not be changed',
    'plugins_edit_identifier' => 'unique identifier (identifier)',
    'The only English identity',
    'plugins_edit_identifier_comment' => 'widget can not duplicate existing plug-in ID. You can use letters, numbers, underscores name, can not contain other symbols or special characters, maximum 40 bytes',
    'plugins_edit_adminid' => 'backstage privilege level (adminid)',
    'plugins_edit_adminid_comment' => 'lowest privilege level required Manager plug-in interface that comes with the plug-in parameters required by the program. Note: The plug-in module has its own backstage permission settings, and therefore not subject to this restriction ',
    'plugins_edit_directory' => 'plugin directory (directory)',
    'plugins_edit_directory_comment' => 'plug-ins (including the front and back) with respect to the source / plugin / relative path must be "/" at the end, otherwise it will generate an error. If you do not specify this setting, the default plug-in front desk procedures are placed in the source / plugin / in. ',
    'plugins_edit_description' => 'plug-in descriptor (description)',
    'plugins_edit_description_comment' => 'plug brief description, up to 100 bytes, an optional fill',
    'plugins_edit_langexists' => 'plug-in language packs',
    'plugins_edit_langexists_comment' => 'If a plug-existence of the language pack, select "Yes"',
    'plugins_edit_modules' => 'plug-in modules and navigation',
    'plugins_edit_modules_name' => 'program module (required)',
    'plugins_edit_modules_menu' => 'link name',
    'plugins_edit_modules_menu_url' => 'link URL',
    'plugins_edit_modules_navtitle' => 'navigation instructions',
    'plugins_edit_modules_navicon' => 'navigation icons',
    'plugins_edit_modules_navsubname' => 'vice navigation name',
    'plugins_edit_modules_navsuburl' => 'vice navigation links',
    'plugins_edit_modules_type' => 'module type',
    'plugins_edit_modules_type_1' => 'main navigation project',
    'plugins_edit_modules_type_2' => '',
    'plugins_edit_modules_type_5' => 'Main Navigation Project - plug-in menu',
    'plugins_edit_modules_type_23' => 'at the bottom of the navigation project',
    'plugins_edit_modules_type_24' => 'homes navigation project',
    'plugins_edit_modules_type_25' => 'quick navigation project',
    'plugins_edit_modules_type_6' => '',
    'plugins_edit_modules_type_7' => 'Personal Settings',
    'plugins_edit_modules_type_8' => '',
    'plugins_edit_modules_type_9' => '',
    'plugins_edit_modules_type_10' => '',
    'plugins_edit_modules_type_3' => 'management center',
    'plugins_edit_modules_type_4' => 'global contain',
    'plugins_edit_modules_type_11' => 'embedded in the page - Limited Edition',
    'plugins_edit_modules_type_12' => 'Special Topics',
    'plugins_edit_modules_type_13' => 'common script',
    'plugins_edit_modules_type_14' => 'sites help',
    'plugins_edit_modules_type_15' => 'Forum Management - Basic',
    'plugins_edit_modules_type_16' => 'Forum Management - tools',
    'plugins_edit_modules_type_17' => 'Personal settings - Personal information',
    'plugins_edit_modules_type_19' => 'Personal settings - integral',
    'plugins_edit_modules_type_18' => '',
    'plugins_edit_modules_type_21' => 'portal management',
    'plugins_edit_modules_type_26' => 'my post',
    'plugins_edit_modules_type_27' => 'top navigation project',
    'plugins_edit_modules_type_28' => 'embedded in the page - Mobile',
    'plugins_edit_modules_type_g1' => 'program links',
    'plugins_edit_modules_type_g2' => 'script',
    'plugins_edit_modules_type_g3' => 'Expand Project',
    'plugins_edit_modules_adminid' => 'usage levels',
    'plugins_edit_modules_include' => 'contains the run',
    'plugins_edit_vars' => 'plug-variable configuration',
    'plugins_edit_vars_title' => 'Configuration name',
    'plugins_edit_vars_title_comment' => 'English can be used to display the plug-in configuration menu, up to 100 bytes. Support language definition here, for example: lang_admincp.php defines \' myaction \' => \'my operating \', then here you can fill in myaction, it is a good multi-language version of the plug of production ',
    'plugins_edit_vars_description' => 'configuration instructions',
    'plugins_edit_vars_description_comment' => 'description of the purpose and the range of this configuration, detailed description of favor widget users to understand the role of this set, up to 255 bytes. Similar profile name here and also supports language definition ',
    'plugins_edit_vars_type' => 'Configuration type',
    'plugins_edit_vars_type_number' => 'digital (number)',
    'plugins_edit_vars_type_text' => 'string (text)',
    'plugins_edit_vars_type_textarea' => 'text (textarea)',
    'plugins_edit_vars_type_radio' => 'switch (radio)',
    'plugins_edit_vars_type_select' => 'radio selection (select)',
    'plugins_edit_vars_type_selects' => 'Multiple Choice (selects)',
    'plugins_edit_vars_type_color' => 'color (color)',
    'plugins_edit_vars_type_date' => 'Date (date)',
    'plugins_edit_vars_type_datetime' => 'Date / Time (datetime)',
    'plugins_edit_vars_type_forum' => 'Forum Radio (forum)',
    'plugins_edit_vars_type_forums' => 'multiple choice section (forums)',
    'plugins_edit_vars_type_group' => 'User Group radio (group)',
    'plugins_edit_vars_type_groups' => 'User Group multiple choice (groups)',
    'plugins_edit_vars_type_extcredit' => 'extension points (extcredit)',
    'plugins_edit_vars_type_forum_text' => 'Forum / string (forum_text)',
    'plugins_edit_vars_type_forum_textarea' => 'Forum / text (forum_textarea)',
    'plugins_edit_vars_type_forum_radio' => 'Forum / switch (forum_radio)',
    'plugins_edit_vars_type_forum_select' => 'Forum / radio selection (forum_select)',
    'plugins_edit_vars_type_group_text' => 'User Group / strings (group_text)',
    'plugins_edit_vars_type_group_textarea' => 'User Group / text (group_textarea)',
    'plugins_edit_vars_type_group_radio' => 'User Group / switch (group_radio)',
    'plugins_edit_vars_type_group_select' => 'User Group / radio selection (group_select)',
    'plugins_edit_vars_multiselect_comment' => 'hold down the CTRL multiple choice',
    'plugins_edit_vars_type_comment' => 'Set this configuration data type for the program to check and filter the appropriate configuration values',
    'plugins_edit_vars_variable' => 'configuration variable name',
    'plugins_edit_vars_variable_comment' => 'set the variable name of the configuration items for plug-in calls, including English, numbers and underscores, in a plug-in with the need to maintain the uniqueness of the variable name, up to 40 bytes',
    'plugins_edit_vars_extra' => 'Extended Settings',
    'plugins_edit_vars_extra_comment' => 'only effective when configuring type "select (select)", is used to set option values. Index options in front of the equal sign (recommended), was behind for the content, such as: <br/><i>1 = Optical Mouse<br/>2 = mechanical mouse <br/> 3 = No Mouse </i>< br /> Note: Do not modify the mapping between the index and the contents of the options is determined after, but still can add options. To swap the order, you can move up and down the whole line position to achieve',
    'plugins_import_default' => 'default',
    'plugins_import_installtype_1' => 'plug-in',
    'plugins_import_installtype_2' => 'The following',
    'plugins_import_installtype_3' => 'methods of installation, select',
    'plugins_import_license' => 'licensing agreement',
    'plugins_import_agree' => 'I agree',
    'plugins_import_pass' => 'I do not agree',
    'plugins_conflict_view' => 'View details',
    'plugins_conflict_info' => 'Contact the Author',
    'plugins_module_sample' => "<span title = 'download module template file'> [&darr;] </span>",
    'plugins_find_newversion' => 'found in the new',
    'plugins_online_update' => 'Click Online install the new version',
    'plugins_list_available' => 'enabled plug',
    'plugins_list_unavailable' => 'not enabled plug',
    'plugins_list_new' => 'does not installed plug-ins',
    'plugins_enable_succeed' => 'plug-enabled',
    'plugin_not_found' => 'plugin not found',
    'plugins_install_succeed' => 'plugin successfully installed! <br/> order to use this plugin, you may also need to upload or modify the file or template, please see the installation of the plug-in instructions <br/><br/><a href="http://addon.discuz.com?view=plugins"> Click here to return to the application center </a><br/> ',
    'plugin_file_error' => 'plugin file is missing',
    'plugins_edit_identifier_invalid' => 'unique identifier you entered is not lawful or duplicate existing plug-in',
    'plugins_upgrade_succeed' => 'plug-in successfully updated to {toversion} <br/><br/><a href="http://addon.discuz.com?view=plugins"> Click here to return to the application center </a><br/> ',
    'plugins_edit_name_invalid' => 'You have not entered the plug-name',
    'plugins_edit_succeed' => 'plug-in configuration updated successfully',
    'plugins_delete_succeed' => 'widget successfully uninstalled! <br/> To uninstall this plugin, you may also need to remove or modify the file or template, please see the installation instructions of the plug-in ',
    'plugins_conflict' => 'plugin enabled</h4><br/> Tips: you just plug enabled embedding common point and some plug-ins exist. Although common embedded point is a normal situation, but if you encounter widget is not working, please contact plugin author. <a href="javascript:;" onclick="display(\'conflict\')"> [Click to view]</a><br/><div id="conflict" style="display: none"><br/>{plugins}<br/></div><br/>',
    'plugins_disable_succeed' => 'plug-in has been closed',
    'plugins_import_var_invalid' => 'embedded point name of the plug is not legitimate, you can not be imported',
    'plugins_import_identifier_duplicated' => 'you want to import plugin ({plugin_name}) already installed',
    'plugins_import_version_invalid_confirm' => 'The plug-in for Discuz! {Cur_version} with the current version ({set_version}) is inconsistent, you sure you want to install it? <br /> If this plug-in installation instructions are not included modify the contents of the file is a description of this plug-in for green plug-ins, you can rest assured that installation ',
    'plugins_import_version_invalid' => 'The plug-in for Discuz! {Cur_version} with the current version ({set_version}) inconsistent',
    'plugins_import_succeed' => 'plug-in data import was successful! <br/> order to use this plugin, you may also need to upload or modify the file or template, please see the installation instructions of the plug-ins',
    'plugins_config_upgrade_confirm' => 'Are you sure you want to {pluginname} {version} {toversion} plugin update to do? ',
    'plugins_config_upgrade_missed' => 'This plugin has been updated to the latest version<br /><br /><a href="http://addon.discuz.com?view=plugins">Click here to return to the application center</a><br />',
    'plugins_upgrade_var_invalid' => 'embedded point name of the plug is not legitimate, can not be updated',
    'plugins_setting_succeed' => 'plug-in parameter settings updated successfully',
    'plugins_setting_module_nonexistence' => 'specified plug-in management module file ({modfile}) absence or presence of a syntax error, please check that the plug-in complete upload',
    'plugins_add_succeed' => 'widget has been successfully added, continue to make detailed settings',
    'plugins_nonexistence' => 'You are about to carry out the operation: the design plug-ins. please select plug-ins: ',
    'plugin_donot_edit' => 'not allowed to edit',
    'plugins_edit_directory_invalid' => 'plugin directory you entered is illegal or does not use the "/" at the end',
    'plugins_edit_language_invalid' => 'plug-in language pack file ({langfile}) does not exist',
    'plugins_edit_modules_name_invalid' => 'program module name you entered is not lawful',
    'plugins_edit_modules_duplicated' => 'program module name you entered duplicate an existing module',
    'plugins_edit_var_invalid' => 'you entered configuration variable name is not valid or repeat',
    'plugins_delete_error' => 'You can not uninstall the system plug. ',
    'plugins_delete_confirm' => 'Are you sure you want to uninstall {pluginname} {toversion} plugins? <br /> <br /> please select the reason that you uninstall the application, so that we can provide a better future for your application: <br /> <br /> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "1" /> function does not satisfy the requirement </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "2" /> Interface unsightly </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "3" /> Efficiency runs slower </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "4" /> found a better application </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "5" /> pure trial now unload </ label> ',
    'Styles_delete_confirm' => 'Are you sure you want to uninstall these styles? <br /> <br /> please select the reason that you uninstall the application, so that we can provide a better future for your application: <br /> <br /> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "1" /> function does not satisfy the requirement </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "2" /> Interface unsightly </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "3" /> Efficiency runs slower </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "4" /> found a better application </ label> <label> <input name = "uninstallreason []" class = "checkbox" type = "checkbox" value = "5" /> pure trial now unload </ label> ',
    'pluginvar_not_found' => 'plug-variable is not found',
    'plugins_edit_var_title_invalid' => 'You did not enter configuration name',
    'plugins_edit_vars_succeed' => 'plug-variable configuration updated successfully',
    'plugins_edit_vars_invalid' => 'plug-in configuration variable name is not valid or has been occupied by',
    'plugins_validator_noupdate' => 'does not detect the new version of the plug',
    'plugins_script_magic' => 'props script',
    'plugins_script_cron' => 'Scheduled Tasks script',
    'plugins_script_adv' => 'ad script',
    'plugins_script_task' => 'Site task script',
    'plugins_script_secqaa' => 'verification quiz script',
    'plugins_script_seccode' => 'Code script',
    'plugins_script_navigation' => 'navigation section embedded script',
    'plugins_script_repeat' => 'duplicate file names',
    'plugins_script_add' => 'Add',
    'plugins_script_delete' => 'Delete',
);
?>